spring:
  application:
    name: file-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/file-service?authSource=admin
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
  port: 8083
  servlet:
    context-path: /file

app:
  file:
    storage-dir-avatar: D:/workspace/media/
    storage-dir-video: D:/workspace/media-video/
    download-prefix: http://localhost:8083/file/media/download/
